Repository reach/reach-ui, pull requests merged in 2019-12, with the labels that each got.

#387 [Tooltip] Make `ref` optional on `useTooltip` hook types
  packages/tooltip/index.d.ts
Labels: bug

#384 [all] Add repository infos to packages manifest
  packages/alert-dialog/package.json
  packages/alert/package.json
  packages/auto-id/package.json
  packages/combobox/package.json
  packages/component-component/package.json
  packages/dialog/package.json
  packages/menu-button/package.json
  packages/popover/package.json
  packages/portal/package.json
  packages/rect/package.json
  packages/skip-nav/package.json
  packages/slider/package.json
  packages/tabs/package.json
  packages/tooltip/package.json
  packages/utils/package.json
  packages/visually-hidden/package.json
  packages/window-size/package.json
Labels: enhancement

#397 @reach/menu-button: use hooks + descendants logic for better handling of focus
  package.json
  packages/menu-button/examples/conditional-items.example.js
  packages/menu-button/examples/focus-on-select.example.js
  packages/menu-button/examples/pete-older.png
  packages/menu-button/examples/pete-younger.png
  packages/menu-button/examples/styled.example.js
  packages/menu-button/examples/styled.example.tsx
  packages/menu-button/examples/with-assigned-index.example.js
  packages/menu-button/examples/with-other-tabbables.example.js
  packages/menu-button/examples/with-styled-router.example.tsx
  packages/menu-button/index.d.ts
  packages/menu-button/package.json
  packages/menu-button/src/index.js
  packages/menu-button/styles.css
  website/src/pages/menu-button.mdx
  yarn.lock
Labels: bug, enhancement

#389 @reach/portal: Replace component-component with hooks
  packages/portal/package.json
  packages/portal/src/index.js
Labels: enhancement

#410 Describe how to import styles in dialog's docs
  website/src/pages/dialog.mdx
Labels: docs
