Repository reach/reach-ui, pull requests merged in 2019-10, with the labels that each got.

#263 [Rect] (docs) Fix small documentation issue
  www/src/pages/rect.mdx
Labels: docs

#169 [AlertDialog] - forwardRef for AlertDialogOverlay/AlertDialogContent
  packages/alert-dialog/src/index.js
Labels: stale

#172 @reach/rect: Resubscribe when nodeRef changes
  packages/rect/src/index.js
Labels: enhancement

#229 Fix to allow storybook build and view in IE11
  packages/dialog/examples/dropdown.example.js
  packages/menu-button/examples/with-tooltip.example.js
  packages/tooltip/examples/animated.example.js
Labels: stale

#271 Update docs to use hooks
  www/src/pages/alert-dialog.mdx
  www/src/pages/alert.mdx
  www/src/pages/combobox.mdx
  www/src/pages/dialog.mdx
  www/src/pages/funding.mdx
  www/src/pages/index.mdx
  www/src/pages/menu-button.mdx
  www/src/pages/rect.mdx
  www/src/pages/skip-nav.mdx
  www/src/pages/styling.mdx
  www/src/pages/tabs.mdx
Labels: docs

#292 MenuButton: Allow user to set MenuButton ID
  packages/menu-button/examples/basic.example.js
  packages/menu-button/src/index.js
Labels: bug

#154 Account for possible scrollbars in the Tooltip triangle sample
  packages/tooltip/examples/triangle.example.js
Labels: bug

#291 Auto-renew the copyright year on the website
  www/src/components/layout.js
Labels: docs

#286 Added link to portal page in the docs (issue #192)
  www/src/components/layout.js
Labels: docs

#295 tooltip: Pass through events and ref to the tooltip trigger
  packages/tooltip/examples/basic.example.js
  packages/tooltip/src/index.js
Labels: bug

#290 New slider component
  .storybook/config.js
  README.md
  package.json
  packages/slider/.babelrc
  packages/slider/.eslintignore
  packages/slider/examples/basic.example.js
  packages/slider/examples/contained-handle.example.js
  packages/slider/examples/controlled-audio-progress.example.js
  packages/slider/examples/controlled.example.js
  packages/slider/examples/utils.js
  packages/slider/examples/vertical.example.js
  packages/slider/examples/with-steps.example.js
  packages/slider/examples/with-tooltip.example.js
  packages/slider/index.d.ts
  packages/slider/package.json
  packages/slider/src/index.js
  packages/slider/styles.css
  www/package.json
  www/src/components/app.css
  www/src/components/layout.js
  www/src/components/mdx-layout.js
  www/src/pages/slider.mdx
  www/yarn.lock
  yarn.lock
Labels: docs, enhancement

#300 Resolve packages names to example imports
  .storybook/webpack.config.js
  packages/alert/examples/basic.example.js
  packages/combobox/examples/basic.example.js
  packages/combobox/examples/controlled.example.js
  packages/combobox/examples/lots-of-elements.example.js
  packages/combobox/examples/no-popover.example.js
  packages/combobox/examples/with-button.example.js
  packages/component-component/examples/lifecycles.example.js
  packages/component-component/examples/state.example.js
  packages/component-component/examples/todo-list.example.js
  packages/dialog/examples/aria-hides-content.example.js
  packages/dialog/examples/autofocus.example.js
  packages/dialog/examples/basic.example.js
  packages/dialog/examples/change-styles.example.js
  packages/dialog/examples/destroy-trigger.example.js
  packages/dialog/examples/dismiss.example.js
  packages/dialog/examples/dropdown.example.js
  packages/dialog/examples/long-content.example.js
  packages/dialog/examples/nested.example.js
  packages/dialog/examples/no-tabbables.example.js
  packages/menu-button/examples/basic.example.js
  packages/menu-button/examples/conditional-items.example.js
  packages/menu-button/examples/long-text.example.js
  packages/menu-button/examples/non-menu-children.example.js
  packages/menu-button/examples/render-callback.example.js
  packages/menu-button/examples/with-links.example.js
  packages/menu-button/examples/with-other-tabbables.example.js
  packages/menu-button/examples/with-tooltip.example.js
  packages/popover/examples/basic.example.js
  packages/portal/examples/basic.example.js
  packages/rect/examples/basic.example.js
  packages/rect/examples/pin.example.js
  packages/rect/examples/use-rect.example.js
  packages/slider/examples/basic.example.js
  packages/slider/examples/contained-handle.example.js
  packages/slider/examples/controlled-audio-progress.example.js
  packages/slider/examples/controlled.example.js
  packages/slider/examples/vertical.example.js
  packages/slider/examples/with-steps.example.js
  packages/slider/examples/with-tooltip.example.js
  packages/tabs/examples/animated-bar.example.js
  packages/tabs/examples/basic.example.js
  packages/tabs/examples/controlled.example.js
  packages/tabs/examples/disabled.example.js
  packages/tooltip/examples/animated.example.js
  packages/tooltip/examples/basic.example.js
  packages/tooltip/examples/triangle.example.js
  packages/visually-hidden/examples/basic.example.js
  packages/window-size/examples/basic.example.js
Labels: enhancement

#301 Component² > hooks
  packages/alert-dialog/examples/basic.example.js
  packages/alert-dialog/package.json
  packages/alert-dialog/src/index.js
  packages/alert/examples/LoremIpsum.js
  packages/alert/examples/basic.example.js
  packages/alert/package.json
  packages/alert/src/index.js
  packages/auto-id/package.json
  packages/combobox/package.json
  packages/combobox/src/index.js
  packages/component-component/package.json
  packages/dialog/examples/aria-hides-content.example.js
  packages/dialog/examples/autofocus.example.js
  packages/dialog/examples/basic.example.js
  packages/dialog/examples/destroy-trigger.example.js
  packages/dialog/examples/dismiss.example.js
  packages/dialog/examples/dropdown.example.js
  packages/dialog/examples/long-content.example.js
  packages/dialog/examples/nested.example.js
  packages/dialog/examples/no-tabbables.example.js
  packages/dialog/package.json
  packages/dialog/src/index.js
  packages/menu-button/package.json
  packages/menu-button/src/index.js
  packages/popover/package.json
  packages/popover/src/index.js
  packages/portal/package.json
  packages/rect/examples/pin.example.js
  packages/rect/package.json
  packages/rect/src/index.js
  packages/skip-nav/package.json
  packages/slider/src/index.js
  packages/tabs/package.json
  packages/tooltip/examples/with-disabled-button.example.js
  packages/tooltip/package.json
  packages/utils/package.json
  packages/utils/src/index.js
  packages/visually-hidden/package.json
  packages/window-size/package.json
  packages/window-size/src/index.js
  www/src/pages/rect.mdx
  www/yarn.lock
  yarn.lock
Labels: enhancement

#302 Update base deps
  package.json
  packages/dialog/examples/dropdown.example.js
  yarn.lock
Labels: housekeeping

#303 Update deps and Github stale rules
  .github/stale.yml
  package.json
  yarn.lock
Labels: housekeeping

#304 Add type="button" for tabs by default (#165)
  .github/stale.yml
  packages/tabs/src/index.js
Labels: bug

#305 alert: allow forwarded refs to alerts (#214)
  packages/alert/src/index.js
  packages/dialog/examples/with-dialog-overlay.example.js
Labels: enhancement

#307 menu-button: Prevent unattached refs from triggering errors
  packages/menu-button/src/index.js
Labels: bug

#308 Export Slider* constants for use in user code
  packages/slider/examples/vertical.example.js
  packages/slider/examples/with-steps.example.js
  packages/slider/src/index.js
Labels: enhancement

#311 window-size: Extract to a new useWindowSize hook
  packages/window-size/examples/hook.example.js
  packages/window-size/src/index.js
  www/src/pages/window-size.mdx
Labels: enhancement

#313 Add and include all package TS definitions
  packages/alert-dialog/index.d.ts
  packages/alert-dialog/package.json
  packages/alert/index.d.ts
  packages/alert/package.json
  packages/auto-id/package.json
  packages/combobox/index.d.ts
  packages/combobox/package.json
  packages/dialog/index.d.ts
  packages/dialog/package.json
  packages/menu-button/index.d.ts
  packages/menu-button/package.json
  packages/popover/index.d.ts
  packages/popover/package.json
  packages/portal/index.d.ts
  packages/portal/package.json
  packages/rect/index.d.ts
  packages/rect/package.json
  packages/skip-nav/index.d.ts
  packages/skip-nav/package.json
  packages/slider/package.json
  packages/tabs/index.d.ts
  packages/tabs/package.json
  packages/tooltip/index.d.ts
  packages/tooltip/package.json
  packages/visually-hidden/index.d.ts
  packages/visually-hidden/package.json
  packages/window-size/index.d.ts
  packages/window-size/package.json
Labels: enhancement

#310 MenuButton: accept pass-through props on outer menu component
  packages/menu-button/src/index.js
Labels: enhancement

#319 Fix tooltips flicker
  packages/tooltip/examples/with-dialog.example.js
  packages/tooltip/src/index.js
Labels: bug

#317 Dialog: Add warnings and documentation to catch missing labels
  packages/dialog/examples/aria-hides-content.example.js
  packages/dialog/examples/autofocus.example.js
  packages/dialog/examples/basic.example.js
  packages/dialog/examples/change-styles.example.js
  packages/dialog/examples/destroy-trigger.example.js
  packages/dialog/examples/dismiss.example.js
  packages/dialog/examples/dropdown.example.js
  packages/dialog/examples/long-content.example.js
  packages/dialog/examples/nested.example.js
  packages/dialog/examples/no-tabbables.example.js
  packages/dialog/examples/with-dialog-overlay.example.js
  packages/dialog/src/index.js
  website/src/pages/dialog.mdx
Labels: docs, enhancement

#320 Import styles as users do in examples
  .storybook/webpack.config.js
  packages/alert-dialog/examples/basic.example.js
  packages/alert/examples/basic.example.js
  packages/combobox/examples/basic.example.js
  packages/combobox/examples/controlled.example.js
  packages/combobox/examples/lots-of-elements.example.js
  packages/combobox/examples/no-popover.example.js
  packages/combobox/examples/token-input.js
  packages/combobox/examples/with-button.example.js
  packages/dialog/examples/aria-hides-content.example.js
  packages/dialog/examples/autofocus.example.js
  packages/dialog/examples/basic.example.js
  packages/dialog/examples/change-styles.example.js
  packages/dialog/examples/destroy-trigger.example.js
  packages/dialog/examples/dismiss.example.js
  packages/dialog/examples/dropdown.example.js
  packages/dialog/examples/long-content.example.js
  packages/dialog/examples/nested.example.js
  packages/dialog/examples/no-tabbables.example.js
  packages/dialog/examples/with-dialog-overlay.example.js
  packages/menu-button/examples/basic.example.js
  packages/menu-button/examples/conditional-items.example.js
  packages/menu-button/examples/long-text.example.js
  packages/menu-button/examples/non-menu-children.example.js
  packages/menu-button/examples/render-prop.example.js
  packages/menu-button/examples/with-links.example.js
  packages/menu-button/examples/with-other-tabbables.example.js
  packages/menu-button/examples/with-tooltip.example.js
  packages/slider/examples/basic.example.js
  packages/slider/examples/contained-handle.example.js
  packages/slider/examples/controlled-audio-progress.example.js
  packages/slider/examples/controlled.example.js
  packages/slider/examples/vertical.example.js
  packages/slider/examples/with-steps.example.js
  packages/slider/examples/with-tooltip.example.js
  packages/tabs/examples/animated-bar.example.js
  packages/tabs/examples/basic.example.js
  packages/tabs/examples/controlled.example.js
  packages/tabs/examples/disabled.example.js
  packages/tooltip/examples/animated.example.js
  packages/tooltip/examples/basic.example.js
  packages/tooltip/examples/triangle.example.js
  packages/tooltip/examples/with-disabled-button.example.js
Labels: docs

#334 Fix Tooltip TypeScript definition
  packages/tooltip/index.d.ts
Labels: bug

#337 Add installation and import section to combobox docs
  website/src/pages/combobox.mdx
Labels: docs

#344 Make visually hidden render as span
  packages/visually-hidden/src/index.js
Labels: bug
