Repository reach/reach-ui, pull requests merged in 2019-11, with the labels that each got.

#352 [@reach/dialog] add `allowPinchZoom` prop to TypeScript definition
  packages/dialog/index.d.ts
Labels: enhancement

#362 Include @reach/utils types when publishing to npm
  packages/utils/package.json
Labels: enhancement

#364 Improve auto-id for server rendering and concurrent mode
  packages/auto-id/src/index.js
Labels: enhancement

#363 Add typescript config for storybook and testing
  .storybook/config.js
  .storybook/webpack.config.js
  package.json
  packages/tabs/examples/basic-typed.example.tsx
  packages/tabs/examples/controlled-typed.example.tsx
  packages/tabs/index.d.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#373 docs(combobox) Update incorrect package name
  website/src/pages/combobox.mdx
Labels: docs

#378 visually-hidden: Add guard for word wrapping
  packages/visually-hidden/src/index.js
Labels: bug

#335 [@reach/tooltip] Simplify Tooltip statechart management
  packages/tooltip/src/index.js
Labels: enhancement

#382 Fix typo in Dialog docs
  website/src/pages/dialog.mdx
Labels: docs

#377 tooltip: add document event listener to hide tooltip on escape
  packages/tooltip/src/index.js
Labels: bug
