Repository reach/reach-ui, pull requests merged in 2020-06, with the labels that each got.

#584 fix(tabs): wait for TabPanel to mount before setting `hidden`
  packages/tabs/src/index.tsx
Labels: Status: Investigation, Type: Bug

#609 [popover] Fix stuck focus
  packages/popover/src/index.tsx
Labels: Type: Bug

#583 fix(slider): prevent keyboard events when disabled
  packages/slider/__tests__/slider.test.tsx
  packages/slider/src/index.tsx
Labels: Status: Investigation, Type: Bug

#622 rect: Fix issues with the observer between renders
  packages/alert/src/index.tsx
  packages/rect/examples/change-observed-ref.example.tsx
  packages/rect/package.json
  packages/rect/src/index.tsx
  packages/utils/src/index.tsx
  yarn.lock
Labels: Type: Bug

#619 Dont try to use .relatedTarget of the mousedown event
  packages/menu-button/src/index.tsx
Labels: Type: Enhancement
