Repository reach/reach-ui, pull requests merged in 2020-11, with the labels that each got.

#700 [menu-button] Fixed popover closing when clicking outside
  packages/menu-button/src/index.tsx
Labels: Type: Bug

#680 [Descendants] Fix typo
  packages/descendants/README.md
  packages/descendants/src/index.tsx
Labels: Type: Documentation

#667 Fix comment typo in Popover package
  packages/popover/src/index.tsx
Labels: Type: Documentation

#688 Add `as` property to VisuallyHidden
  packages/visually-hidden/__tests__/visually-hidden.test.tsx
  packages/visually-hidden/examples/basic.example.tsx
  packages/visually-hidden/examples/with-as-prop.example.tsx
  packages/visually-hidden/src/index.tsx
  website/src/pages/visually-hidden.mdx
Labels: Type: Enhancement

#689 Change the root element of the hidden message to div
  packages/alert/src/index.tsx
Labels: Type: Bug

#694 [slider] Fix #693 by capturing mutable value sliderRef.current
  packages/slider/src/index.tsx
Labels: Type: Bug

#673 Remove slider width styling
  packages/slider/styles.css
Labels: Type: Enhancement

#708 [Utils] export imported types as types
  packages/utils/src/index.tsx
Labels: Type: Bug
