Repository reach/reach-ui, pull requests merged in 2020-01, with the labels that each got.

#429 [dialog] Add allowPinchZoom docs description
  website/src/pages/dialog.mdx
Labels: docs

#428 [Utils] Remove the mandatory of "as" type
  packages/utils/src/types.tsx
Labels: bug

#426 [Combobox] Fix return type of ComboboxOptionText
  packages/combobox/src/index.tsx
Labels: bug

#424 Remove double "the"
  website/src/pages/animation.mdx
Labels: docs

#437 Allow passing the style property to MenuPopover again.
  packages/menu-button/src/index.tsx
Labels: enhancement

#442 Update incorrect custom TabPanel example
  website/src/pages/tabs.mdx
Labels: docs

#329 New component: @reach/checkbox
  README.md
  packages/checkbox/README.md
  packages/checkbox/examples/basic-mixed.example.js
  packages/checkbox/examples/checklist.example.js
  packages/checkbox/examples/custom-composed.example.js
  packages/checkbox/examples/custom-group.example.js
  packages/checkbox/examples/custom-pseduo.css
  packages/checkbox/examples/custom-pseudo.example.js
  packages/checkbox/examples/disabled.example.js
  packages/checkbox/examples/hook.example.tsx
  packages/checkbox/package.json
  packages/checkbox/src/custom.tsx
  packages/checkbox/src/index.tsx
  packages/checkbox/src/mixed.tsx
  packages/checkbox/styles.css
  packages/checkbox/tsconfig.build.json
  packages/utils/src/index.tsx
  packages/utils/src/types.tsx
  tsconfig.json
  website/package.json
  website/src/pages/tabs.mdx
  yarn.lock
Labels: enhancement
