Repository reach/reach-ui, pull requests merged in 2020-04, with the labels that each got.

#535 Docs: Fix Rect-Props hrefs
  website/src/pages/rect.mdx
Labels: docs

#504 [Combobox] Add aria-label to examples
  packages/combobox/__tests__/combobox.test.tsx
  packages/combobox/examples/basic-ts.example.tsx
  packages/combobox/examples/basic.example.js
  packages/combobox/examples/controlled-ts.example.tsx
  packages/combobox/examples/controlled.example.js
  packages/combobox/examples/lots-of-elements.example.js
  packages/combobox/examples/no-popover.example.js
  packages/combobox/examples/open-on-focus.example.js
  packages/combobox/examples/token-input.js
  packages/combobox/examples/with-button.example.js
  packages/combobox/src/index.tsx
  website/src/pages/combobox.mdx
Labels: docs

#484 Add positionRight helper to Popover
  packages/popover/src/index.tsx
Labels: enhancement, stale

#546 [Combobox] Clear value when input focused after interacting with popover
  packages/combobox/src/index.tsx
Labels: bug

#544 Listbox docs: fix typos
  website/src/pages/listbox.mdx
Labels: docs

#538 Improve Disclosure component tests
  packages/disclosure/__tests__/disclosure.test.tsx
Labels: Type: Enhancement

#550 [MenuButton] Don't default to focusing a MenuItem when using mouse
  packages/menu-button/__tests__/menu-button.test.tsx
  packages/menu-button/src/index.tsx
Labels: Type: Enhancement

#553 Remove duplicate CSS declaration
  packages/listbox/styles.css
Labels: Type: Enhancement

#549 add missing type dep
  packages/utils/package.json
Labels: Type: Enhancement

#551 accordion: improve tests
  packages/accordion/__tests__/accordion.test.tsx
Labels: Type: Enhancement
