Repository reach/reach-ui, pull requests merged in 2020-05, with the labels that each got.

#574 portal: fix TypeError when using hot-loader
  packages/portal/src/index.tsx
Labels: Type: Bug

#570 [Listbox] Hide input that documentation claims is hidden
  packages/listbox/__tests__/listbox.test.tsx
  packages/listbox/src/index.tsx
Labels: Status: Awaiting Response, Type: Bug

#572 Use type button by default in Tab component
  packages/tabs/__tests__/tabs.test.tsx
  packages/tabs/src/index.tsx
Labels: Type: Enhancement

#587 [Dialog] Fix initialFocusRef docs by changing the prop heading to the DialogOverlay component
  website/src/pages/dialog.mdx
Labels: Type: Documentation

#588 fix(build): dont use `Array.flatMap`
  scripts/build.ts
  scripts/utils.ts
Labels: Type: Housekeeping

#585 fix(website): remove redundant :root selector in app.scss of website
  website/src/styles/app.scss
Labels: Type: Documentation

#581 docs: updated the README.md with new link of yarn install instructions
  README.md
Labels: Type: Documentation

#599 fix(website): update lock file
  website/package.json
  website/yarn.lock
Labels: Type: Documentation

#597 Fix tabs.mdx animated example
  website/src/pages/tabs.mdx
Labels: Type: Documentation
