Repository reach/reach-ui, pull requests merged in 2020-03, with the labels that each got.

#496 [Combobox] Remove unused __ComboboxPopoverProps type
  packages/combobox/src/index.tsx
Labels: enhancement

#494 Docs: fix animation examples to not use HOCs in the render
  website/src/pages/animation.mdx
  website/src/pages/dialog.mdx
Labels: docs

#474 @reach/listbox
  .storybook/manager.js
  packages/auto-id/src/index.ts
  packages/dialog/examples/autofocus.example.js
  packages/dialog/examples/basic.example.js
  packages/dialog/examples/change-styles.example.js
  packages/dialog/examples/destroy-trigger.example.js
  packages/dialog/examples/dropdown.example.js
  packages/dialog/examples/long-content.example.js
  packages/listbox/NOTES.md
  packages/listbox/README.md
  packages/listbox/examples/basic-strict-mode.example.tsx
  packages/listbox/examples/basic.example.js
  packages/listbox/examples/composed.example.tsx
  packages/listbox/examples/controlled.example.tsx
  packages/listbox/examples/grouped-composed-label.example.js
  packages/listbox/examples/grouped.example.js
  packages/listbox/examples/styled.example.js
  packages/listbox/examples/with-form.example.tsx
  packages/listbox/examples/with-nested-tabbables.example.tsx
  packages/listbox/package.json
  packages/listbox/src/NOTES.md
  packages/listbox/src/index.tsx
  packages/listbox/src/machine.ts
  packages/listbox/styles.css
  packages/listbox/tsconfig.build.json
  packages/menu-button/examples/basic.example.js
  packages/menu-button/src/index.tsx
  packages/utils/src/index.tsx
  packages/utils/src/types.tsx
  tsconfig.json
  website/package.json
  website/src/components/Layout.js
  website/src/pages/animation.mdx
  website/src/pages/dialog.mdx
Labels: feature

#515 [Listbox]: add expanded value for ListboxInput render function
  packages/listbox/src/index.tsx
  website/src/pages/listbox.mdx
Labels: enhancement

#518 [Tabs] Update animated example
  packages/tabs/examples/animated-bar.example.js
Labels: docs

#517 [Combobox] Remove escape-regexp dependency
  packages/combobox/package.json
  packages/combobox/src/index.tsx
  yarn.lock
Labels: enhancement

#522 descendants: Remove unnecessary loop
  packages/descendants/src/index.tsx
Labels: enhancement

#516 [Accordion] User event and rendering tests
  packages/accordion/__tests__/accordion.test.tsx
Labels: enhancement

#526 add test for dismiss dialog by clicking overlay
  packages/dialog/__tests__/__snapshots__/dialog.test.tsx.snap
  packages/dialog/__tests__/dialog.test.tsx
Labels: enhancement

#521 [dialog] Fixes #390: Disable tooltip when dialog closes
  packages/dialog/examples/with-tooltip.example.js
  packages/dialog/src/index.tsx
Labels: enhancement

#528 [docs] Fix Modal Dialog Animation examples with Syntax Error
  website/src/pages/animation.mdx
  website/src/pages/dialog.mdx
Labels: docs

#486 tabs: Add support for vertical orientation
  packages/tabs/__tests__/tabs.test.tsx
  packages/tabs/examples/vertical-end.example.tsx
  packages/tabs/examples/vertical-start-rtl.example.tsx
  packages/tabs/examples/vertical-start.example.js
  packages/tabs/examples/wrappers-wild.example.tsx
  packages/tabs/src/index.tsx
  packages/tabs/styles.css
  website/src/pages/tabs.mdx
Labels: feature
