Repository reach/reach-ui, pull requests merged in 2021-03, with the labels that each got.

#752 fix(auto-id): add missing type overload
  packages/auto-id/src/index.tsx
Labels: Type: Enhancement

#761 Add sideEffects false to all packages to enable tree shaking
  packages/accordion/package.json
  packages/alert-dialog/package.json
  packages/alert/package.json
  packages/auto-id/package.json
  packages/checkbox/package.json
  packages/combobox/package.json
  packages/component-component/package.json
  packages/descendants/package.json
  packages/dialog/package.json
  packages/disclosure/package.json
  packages/listbox/package.json
  packages/machine/package.json
  packages/menu-button/package.json
  packages/popover/package.json
  packages/portal/package.json
  packages/rect/package.json
  packages/skip-nav/package.json
  packages/slider/package.json
  packages/tabs/package.json
  packages/tooltip/package.json
  packages/utils/package.json
  packages/utils/src/index.tsx
  packages/visually-hidden/package.json
  packages/window-size/package.json
Labels: Type: Enhancement

#767 tooltip: Fix typo in comments
  packages/tooltip/src/index.tsx
Labels: Type: Documentation

#769 Add *.css files to the list of sideEffect(ful) files
  packages/accordion/package.json
  packages/alert-dialog/package.json
  packages/alert/package.json
  packages/auto-id/package.json
  packages/checkbox/package.json
  packages/combobox/package.json
  packages/component-component/package.json
  packages/descendants/package.json
  packages/dialog/package.json
  packages/disclosure/package.json
  packages/listbox/package.json
  packages/machine/package.json
  packages/menu-button/package.json
  packages/popover/package.json
  packages/portal/package.json
  packages/rect/package.json
  packages/skip-nav/package.json
  packages/slider/package.json
  packages/tabs/package.json
  packages/tooltip/package.json
  packages/visually-hidden/package.json
  packages/window-size/package.json
Labels: Status: Investigation, Type: Bug
