Repository reach/reach-ui, pull requests merged in 2021-07, with the labels that each got.

#807 menu-button(fix): fix selection when assistive tech on
  packages/menu-button/src/index.tsx
Labels: Type: Bug, a11y: VoiceOver

#652 [rect] Consider observe variable before throwing warning
  packages/rect/src/index.tsx
Labels: Help Wanted, Type: Enhancement

#818 Fixed little typo in docs
  packages/auto-id/src/index.tsx
Labels: Type: Documentation
