Repository reach/reach-ui, pull requests merged in 2021-02, with the labels that each got.

#742 fix(tooltip): prevent crashing when using SSR
  packages/tooltip/src/index.tsx
Labels: Type: Bug

#740 [menu-button] Prevent extraneous updates when clicking outside closed menus
  packages/menu-button/src/index.tsx
Labels: Type: Enhancement

#749 ci tweaks
  .codesandbox/templates/reach-ui/package.json
  .codesandbox/templates/reach-ui/src/App.tsx
  .codesandbox/templates/reach-ui/src/CurrentState.tsx
  .codesandbox/templates/reach-ui/src/index.js
Labels: Type: Housekeeping

#732 Replace custom build scripts w/ Preconstruct
  babel.config.js
  package.json
  packages/accordion/package.json
  packages/alert-dialog/package.json
  packages/alert/package.json
  packages/auto-id/package.json
  packages/checkbox/package.json
  packages/combobox/package.json
  packages/component-component/package.json
  packages/descendants/package.json
  packages/dialog/package.json
  packages/disclosure/package.json
  packages/listbox/package.json
  packages/machine/package.json
  packages/menu-button/package.json
  packages/popover/package.json
  packages/portal/package.json
  packages/rect/package.json
  packages/skip-nav/package.json
  packages/slider/package.json
  packages/tabs/package.json
  packages/tooltip/package.json
  packages/utils/package.json
  packages/visually-hidden/package.json
  packages/window-size/package.json
  scripts/build-all.ts
  scripts/build-package.ts
  scripts/build.ts
  tsconfig.json
  yarn.lock
Labels: Type: Housekeeping
